version: "3.3"

services:
  server:
    build:
      context: .
      dockerfile: local.DockerFile
    command: "bin/setup"
    environment:
      - RAILS_ENV=development
    ports:
    - 3010:3000
    volumes:
    - .:/src
    depends_on:
    - postgres
    
  postgres:
    image: postgres:16.1
    restart: unless-stopped
    ports:
    - 6010:5432
    volumes:
    - postgres-data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
  
  local-redis:
    image: redis
    container_name: local-redis
    ports:
      - 6379:6379
  
  sidekiq:
    build:
      context: .
      dockerfile: local.DockerFile
    command: bash -c "sleep 2 && bundle install && bundle exec sidekiq"
    environment:
      - RAILS_ENV=development
    volumes:
    - .:/src
    depends_on:
    - postgres
    - local-redis

  mail:
    container_name: mail
    image: schickling/mailcatcher
    ports:
      - 3003:1080
    volumes:
      - .:/src

volumes:
  postgres-data: